USE team;

/* DROP USERS */
DROP TABLE IF EXISTS USERS;

/* CREATE USERS */
CREATE TABLE USERS (
    USER_NO    		INT   		NOT NULL AUTO_INCREMENT,
    USER_ID    		VARCHAR(60) NOT NULL,
    USER_PW			VARCHAR(64) NOT NULL,
    NAME      		VARCHAR(20) NOT NULL,
    N_NAME   		VARCHAR(24) NOT NULL,
    GENDER      	VARCHAR(2)  NOT NULL,
    EMAIL      		VARCHAR(50) NOT NULL,
    MOBILE      	VARCHAR(11) NOT NULL,
    BIRTHDAY   		VARCHAR(2)  NOT NULL,
    AGREE_CODE      INT   		NOT NULL,
    SNS_TYPE      	VARCHAR(10) NULL,
    JOIN_DATE      	DATE   		NOT NULL,
    PW_MODIFY_DATE  DATE 		NULL,
    SS_ID         	VARCHAR(32) NULL,
    SS_LIMIT_DATE   DATE   		NULL,
    IP 				VARCHAR(30) NULL,
    BANNED_STATE    INT 		NOT NULL,
    PRIMARY KEY(USER_NO)
);