USE team;

/* DROP POINT */
DROP TABLE IF EXISTS POINT_LOG;
DROP TABLE IF EXISTS USER_POINT;

/* DROP USERS */
DROP TABLE IF EXISTS BN_USERS;
DROP TABLE IF EXISTS RT_USERS;
DROP TABLE IF EXISTS SL_USERS;
DROP TABLE IF EXISTS USERS;

/* CREATE USERS */
CREATE TABLE USERS (
    USER_NO    		INT   		NOT NULL AUTO_INCREMENT,
    USER_ID    		VARCHAR(60) NOT NULL,
    USER_PW			VARCHAR(64) NOT NULL,
    NAME      		VARCHAR(20) NOT NULL,
    N_NAME   		VARCHAR(24) NOT NULL,
    GENDER      	VARCHAR(2)  NOT NULL,
    EMAIL      		VARCHAR(50) NOT NULL,
    MOBILE      	VARCHAR(11) NOT NULL,
    BIRTHDAY   		VARCHAR(2)  NOT NULL,
    AGREE_CODE      INT   		NOT NULL,
    SNS_TYPE      	VARCHAR(10),
    JOIN_DATE      	DATE   		NOT NULL,
    PW_MODIFY_DATE  DATE,
    SS_ID         	VARCHAR(32),
    SS_LIMIT_DATE   DATE,
    IP 				VARCHAR(30),
    PRIMARY KEY(USER_NO)
);

CREATE TABLE SL_USERS (
	SL_USER_NO INT NOT NULL,
    USER_ID VARCHAR(60) NOT NULL,
    USER_PW VARCHAR(64) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    N_NAME VARCHAR(24),
    GENDER VARCHAR(2) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    MOBILE VARCHAR(11) NOT NULL,
    BIRTHDAY VARCHAR(8) NOT NULL,
    AGREE_CODE INT NOT NULL,
    SNS_TYPE INT,
    JOIN_DATE DATE NOT NULL,
    SL_DATE DATE NOT NULL,
    IP VARCHAR(30),
    PRIMARY KEY(SL_USER_NO)
);

CREATE TABLE RT_USERS (
	RT_USER_NO INT NOT NULL,
    USER_ID VARCHAR(60) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    RT_DATE DATE NOT NULL
);

CREATE TABLE BN_USERS (
	BANN_NO INT NOT NULL AUTO_INCREMENT,
    USER_NO INT NOT NULL,
    BANN_DATE DATE NOT NULL,
    BANN_PERIOD INT NOT NULL,
    PRIMARY KEY(BANN_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);

/* CREATE POINT */
CREATE TABLE POINT_LOG(
	POINT_LOG_NO INT NOT NULL AUTO_INCREMENT,
    USER_NO INT NOT NULL,
    POINT_LOG VARCHAR(100) NOT NULL,
    POINT_LOG_DATE DATE NOT NULL,
    POINT INT NOT NULL DEFAULT '0',
    PRIMARY KEY(POINT_LOG_NO),
    FOREIGN KEY(USER_NO) REFERENCES USERS(USER_NO) ON DELETE CASCADE
);
